# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resetpasswordtoken',
            old_name='dynamic_url',
            new_name='url_token',
        ),
        migrations.AddField(
            model_name='resetpasswordtoken',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resetpasswordtoken',
            name='reach_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
